// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdbxsikbayiererwtukl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkYnhzaWtiYXlpZXJlcnd0dWtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NjI4NTksImV4cCI6MjA2MTMzODg1OX0.9K2ife5-iBF436r2o9hNX4VQawOhFnSmDfx22H3BTL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);